log:
  level: DEBUG

server:
  host: 0.0.0.0:8000

paste:
  mgo:
    host: mongodb://mongo:27017
    db: paste
    coll: paste

limit:
  code_length: 100000 #字符
  code_count: 5
  image_size: 10 #MB
  image_count: 5